#!/usr/bin/env python3
"""
Stack file management for stacked PR workflow.
Handles YAML parsing, tree building, and stack operations.

Usage:
    stack.py status <repo>              Show stack status with tree
    stack.py get-base <repo> <branch>   Get base branch for a branch
    stack.py add <repo> <branch> <base> Add branch to stack
    stack.py delete <repo> <branch>     Remove branch from stack
    stack.py dependents <repo> <branch> List branches that depend on this one
    stack.py topo-sort <repo>           List branches in topological order
    stack.py validate <repo> <branch> <base>  Check if adding would create cycle
"""
from __future__ import annotations

import sys
import os
from pathlib import Path
from collections import defaultdict
from typing import Optional

STACK_DIR = Path.home() / ".stack"


def get_stack_file(repo: str) -> Path:
    return STACK_DIR / f"{repo}.yaml"


def load_stack(repo: str) -> dict[str, str]:
    """Load stack file, return dict of branch -> base."""
    stack_file = get_stack_file(repo)
    if not stack_file.exists():
        return {}

    branches = {}
    current_branch = None

    with open(stack_file) as f:
        for line in f:
            line = line.rstrip()
            # Skip comments and empty lines
            if not line or line.startswith("#"):
                continue
            # Skip the 'branches:' header
            if line == "branches:":
                continue
            # Branch entry (2-space indent)
            if line.startswith("  ") and not line.startswith("    "):
                # e.g., "  feature/auth:"
                current_branch = line.strip().rstrip(":")
            # Base entry (4-space indent)
            elif line.startswith("    base:") and current_branch:
                base = line.split("base:", 1)[1].strip()
                branches[current_branch] = base

    return branches


def save_stack(repo: str, branches: dict[str, str]) -> None:
    """Save stack to file."""
    STACK_DIR.mkdir(parents=True, exist_ok=True)
    stack_file = get_stack_file(repo)

    with open(stack_file, "w") as f:
        f.write(f"# ~/.stack/{repo}.yaml\n")
        f.write("# Auto-generated by /stack-pr - safe to edit manually\n\n")
        f.write("branches:\n")

        # Sort branches for consistent output
        for branch in sorted(branches.keys()):
            base = branches[branch]
            f.write(f"  {branch}:\n")
            f.write(f"    base: {base}\n\n")


def build_tree(branches: dict[str, str]) -> dict[str, list[str]]:
    """Build parent -> children mapping."""
    children = defaultdict(list)
    for branch, base in branches.items():
        children[base].append(branch)
    # Sort children for consistent display
    for base in children:
        children[base].sort()
    return children


def find_roots(branches: dict[str, str]) -> list[str]:
    """Find root branches (bases not in the stack)."""
    all_branches = set(branches.keys())
    all_bases = set(branches.values())
    # Roots are bases that aren't themselves branches in the stack
    roots = all_bases - all_branches
    return sorted(roots)


def print_tree(
    children: dict[str, list[str]],
    node: str,
    current_branch: Optional[str],
    prefix: str = "",
    is_root: bool = True,
    is_last: bool = True,
    sync_status: Optional[dict[str, str]] = None,
) -> None:
    """Recursively print tree structure."""
    # Build status indicators
    indicators = []
    if node == current_branch:
        indicators.append("(*)")

    if sync_status and node in sync_status:
        status = sync_status[node]
        if status != "ok":
            indicators.append(f"⚠ {status}")

    suffix = " ".join(indicators)
    if suffix:
        suffix = " " + suffix

    # Mark current branch
    arrow = ""
    if node == current_branch:
        arrow = "  ← you are here"

    if is_root:
        # Root node - no connector
        print(f"{node}{suffix}{arrow}")
    else:
        # Child node - use tree connector
        connector = "└── " if is_last else "├── "
        print(f"{prefix}{connector}{node}{suffix}{arrow}")

    # Print children
    node_children = children.get(node, [])
    for i, child in enumerate(node_children):
        is_last_child = i == len(node_children) - 1
        if is_root:
            # Children of root - no prefix yet
            new_prefix = ""
        else:
            new_prefix = prefix + ("    " if is_last else "│   ")
        print_tree(children, child, current_branch, new_prefix, False, is_last_child, sync_status)


def topo_sort(branches: dict[str, str]) -> list[str]:
    """Topological sort of branches (parents before children)."""
    result = []
    visited = set()
    children = build_tree(branches)
    roots = find_roots(branches)

    def visit(node: str) -> None:
        if node in visited:
            return
        visited.add(node)
        if node in branches:  # Only add if it's an actual stack branch
            result.append(node)
        for child in children.get(node, []):
            visit(child)

    for root in roots:
        visit(root)

    return result


def has_cycle(branches: dict[str, str], new_branch: str, new_base: str) -> bool:
    """Check if adding new_branch -> new_base would create a cycle."""
    # Temporarily add the new relationship
    test_branches = dict(branches)
    test_branches[new_branch] = new_base

    # Walk from new_base up the chain, check if we hit new_branch
    visited = set()
    current = new_base
    while current in test_branches:
        if current in visited:
            return True  # Cycle detected
        if current == new_branch:
            return True  # Would create cycle
        visited.add(current)
        current = test_branches[current]

    return False


def get_dependents(branches: dict[str, str], branch: str) -> list[str]:
    """Get all branches that directly or indirectly depend on this branch."""
    children = build_tree(branches)
    result = []

    def collect(node: str) -> None:
        for child in children.get(node, []):
            result.append(child)
            collect(child)

    collect(branch)
    return result


def cmd_status(repo: str, current_branch: str | None = None) -> None:
    """Show stack status."""
    branches = load_stack(repo)

    if not branches:
        print(f"No stack configured for: {repo}")
        print("\nUse `/stack-pr add <base>` to start tracking branches.")
        return

    children = build_tree(branches)
    roots = find_roots(branches)

    print(f"Stack for: {repo}")
    if current_branch:
        in_stack = " (*)" if current_branch in branches else ""
        print(f"Current branch: {current_branch}{in_stack}")
    print()

    for root in roots:
        print_tree(children, root, current_branch)
        print()

    print(f"Branches in stack: {len(branches)}")


def cmd_get_base(repo: str, branch: str) -> None:
    """Get base for a branch."""
    branches = load_stack(repo)
    if branch in branches:
        print(branches[branch])
    else:
        sys.exit(1)


def cmd_add(repo: str, branch: str, base: str) -> None:
    """Add branch to stack."""
    branches = load_stack(repo)

    # Validate
    if has_cycle(branches, branch, base):
        print(f"Error: Adding {branch} → {base} would create a cycle", file=sys.stderr)
        sys.exit(1)

    branches[branch] = base
    save_stack(repo, branches)
    print(f"Added: {branch} → {base}")


def cmd_delete(repo: str, branch: str) -> None:
    """Delete branch from stack."""
    branches = load_stack(repo)

    if branch not in branches:
        print(f"Branch not in stack: {branch}", file=sys.stderr)
        sys.exit(1)

    # Get the base of the deleted branch (for reparenting dependents)
    old_base = branches[branch]

    # Find dependents
    dependents = [b for b, base in branches.items() if base == branch]

    # Remove the branch
    del branches[branch]

    # Reparent dependents to point to the deleted branch's base
    for dep in dependents:
        branches[dep] = old_base

    save_stack(repo, branches)
    print(f"Removed: {branch}")
    if dependents:
        print(f"Reparented to '{old_base}': {', '.join(dependents)}")


def cmd_dependents(repo: str, branch: str) -> None:
    """List direct dependents of a branch."""
    branches = load_stack(repo)
    dependents = [b for b, base in branches.items() if base == branch]
    for dep in dependents:
        print(dep)


def cmd_topo_sort(repo: str) -> None:
    """List branches in topological order."""
    branches = load_stack(repo)
    for branch in topo_sort(branches):
        base = branches[branch]
        print(f"{branch}:{base}")


def cmd_validate(repo: str, branch: str, base: str) -> None:
    """Validate if adding branch -> base would be valid."""
    branches = load_stack(repo)
    if has_cycle(branches, branch, base):
        print("cycle")
        sys.exit(1)
    print("ok")


def main() -> None:
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    cmd = sys.argv[1]

    if cmd == "status" and len(sys.argv) >= 3:
        repo = sys.argv[2]
        current = sys.argv[3] if len(sys.argv) > 3 else None
        cmd_status(repo, current)
    elif cmd == "get-base" and len(sys.argv) == 4:
        cmd_get_base(sys.argv[2], sys.argv[3])
    elif cmd == "add" and len(sys.argv) == 5:
        cmd_add(sys.argv[2], sys.argv[3], sys.argv[4])
    elif cmd == "delete" and len(sys.argv) == 4:
        cmd_delete(sys.argv[2], sys.argv[3])
    elif cmd == "dependents" and len(sys.argv) == 4:
        cmd_dependents(sys.argv[2], sys.argv[3])
    elif cmd == "topo-sort" and len(sys.argv) == 3:
        cmd_topo_sort(sys.argv[2])
    elif cmd == "validate" and len(sys.argv) == 5:
        cmd_validate(sys.argv[2], sys.argv[3], sys.argv[4])
    else:
        print(__doc__)
        sys.exit(1)


if __name__ == "__main__":
    main()
